### ISSUE TITLE
No code initialize vcd_info->vcd_fb

### ISSUE THREAD

**Issue by avifishman** [NTC-CCBG/soc-remote-kvm#3]
https://github.com/NTC-CCBG/soc-remote-kvm/blob/7045d1120f6617318a3463d8a84a516c17d11af7/libvncserver/rfbnpcm750.c#L91
No code initialize vcd_info->vcd_fb, so it stays zero, than in the linux driver drivers/video/compression/hextile.c b/drivers/video/compression/hextile.c
data.framebuf==0 so SETFB fails.

**Comment by maxdog988** [comment]
Did you plug Poleg on the motherboard which has a PCI-E slot?
If you didn’t, this error is because the VCD module cannot get video frame resolution.
*************************************************
In kernel /driver/video/vcd.c :546
        changed = ((vcd->info.hdisp != vcd_get_hres(vcd)) ||
                (vcd->info.vdisp != vcd_get_vres(vcd)));

The resolution always zero!!
*************************************************

Joseph Liu
